spring.application.name=hair

# Configuracao do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/hair-store
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver