ALTER TABLE brand
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE brand SET is_active = TRUE WHERE is_active IS NULL;
UPDATE brand SET created_at = CURRENT_TIMESTAMP WHERE created_at IS NULL;

ALTER TABLE brand
    ALTER COLUMN is_active SET NOT NULL,
    ALTER COLUMN created_at SET NOT NULL;